# Generated by Django 2.2.20 on 2021-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='post_task',
        ),
        migrations.AddField(
            model_name='command',
            name='post_task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
