# Generated by Django 2.2.20 on 2021-09-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210902_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextflowprocess',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
