# Generated by Django 2.2.16 on 2020-12-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201205_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='slug',
        ),
    ]
