# Generated by Django 2.2.20 on 2021-07-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_command_nextflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='can_create_sample',
            field=models.BooleanField(default=False),
        ),
    ]
