# Generated by Django 2.2.20 on 2021-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210523_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='data_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
