# Generated by Django 2.2.20 on 2021-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_command_can_create_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workdirs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
