# Generated by Django 2.2.20 on 2021-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_command_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='requirements',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='command',
            name='run',
            field=models.TextField(default='{}'),
        ),
    ]
