# Generated by Django 2.2.20 on 2021-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_execution_workdirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='terminal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
