# Generated by Django 2.2.16 on 2020-12-11 05:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='', upload_to=core.models.create_filename),
        ),
    ]
