# Generated by Django 2.2.20 on 2021-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_execution_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='run_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='run_status',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
