# Generated by Django 2.2.16 on 2020-12-13 05:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201213_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, validators=[core.models.slug_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=30, unique=True, validators=[core.models.slug_validator]),
        ),
    ]
