# Generated by Django 2.2.20 on 2021-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210727_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='terminal',
            new_name='nf_terminal',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='run_name',
            new_name='process_name',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='run_status',
            new_name='process_status',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='workdirs',
        ),
        migrations.AddField(
            model_name='execution',
            name='process_stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='process_stdout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
