# Generated by Django 2.2.16 on 2021-01-06 15:49

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201213_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('creation_time', models.IntegerField(default=time.time)),
                ('last_modified', models.IntegerField(default=time.time)),
                ('description', models.TextField(blank=True, default='')),
                ('private', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('collections', models.ManyToManyField(related_name='papers', to='core.Collection')),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='CollectionUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('can_execute', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'collection_user_links',
            },
        ),
        migrations.CreateModel(
            name='CollectionGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('can_execute', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Collection')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
            options={
                'db_table': 'collection_group_links',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='groups',
            field=models.ManyToManyField(related_name='collections', through='core.CollectionGroupLink', to='core.Group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to='core.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='users',
            field=models.ManyToManyField(related_name='collections', through='core.CollectionUserLink', to='core.User'),
        ),
    ]
