# Generated by Django 2.2.16 on 2021-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210106_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-creation_time']},
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expiry',
            field=models.IntegerField(default=0),
        ),
    ]
