# Generated by Django 2.2.16 on 2021-01-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='description',
        ),
    ]
