# Generated by Django 2.2.16 on 2021-03-30 09:17

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sample_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('input_schema', models.TextField(default='[]')),
                ('output_schema', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.IntegerField(default=time.time)),
                ('scheduled', models.IntegerField(blank=True, null=True)),
                ('started', models.IntegerField(blank=True, null=True)),
                ('finished', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('warning', models.CharField(blank=True, max_length=300, null=True)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('input', models.TextField(default='{}')),
                ('output', models.TextField(default='{}')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.Collection')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.Process')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.Sample')),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['created'],
            },
        ),
    ]
