SPECIES = {
    "Hs": {"name": "Human", "ensembl": "hsapiens"},
    "Mm": {"name": "Mouse", "ensembl": "mmusculus"},
    "Rn": {"name": "Rat", "ensembl": "rnorvegicus"},
    "Dr": {"name": "Zebrafish", "ensembl": "drerio"},
    "Dm": {"name": "Drosophila", "ensembl": "dmelanogaster"},
    "Sc": {"name": "Yeast", "ensembl": "scerevisiae"},
}

METHODS = [
    "4SU-iCLIP",
    "BrdU-CLIP",
    "CLAP",
    "CLIP",
    "CLIP-seq",
    "FAST-iCLIP",
    "FLASH",
    "HITS-CLIP",
    "PAR-CLIP",
    "RIP",
    "eCLIP",
    "hiCLIP",
    "iCLIP",
    "irCLIP",
    "miCLIP",
    "sCLIP",
    "uvCLAP",
]

CELL_LINES = [
    "293Flp",
    "3T3",
    "786O",
    "A375",
    "BJAB",
    "BMDM",
    "Bcells",
    "CD4 T cells",
    "CD8 T cells",
    "CD8 Tcells",
    "CEM-SS",
    "CEM_SS",
    "CHP-212",
    "COS7",
    "Cal51",
    "DoHH2",
    "E.coli",
    "ESC",
    "Embryonic body",
    "H1",
    "H1299",
    "HAP1",
    "HEK293",
    "HEK293 HR1",
    "HEK293T",
    "HIV IIIB",
    "HUVEC",
    "Head",
    "Hela",
    "Hela nuclear extract",
    "HelaFlp",
    "HepG2",
    "Huh7.5",
    "IMR-32",
    "K562",
    "MCF7",
    "MDA231",
    "MEF",
    "MOLM13",
    "Mutu",
    "N2A",
    "NSC",
    "NSC34",
    "OCI-AML3",
    "P19",
    "Raji",
    "S.aureus",
    "SHSY5Y",
    "SK-N-AS",
    "SK1 yeast",
    "SMI",
    "TCMK",
    "THP-1",
    "U251",
    "U266",
    "U2932",
    "U2OS",
    "Usti_filaments",
    "Ustilago filaments",
    "astrocytes",
    "brain",
    "brainstem",
    "cerebellum",
    "cortex",
    "dermal fibroblasts",
    "drosophila",
    "fission yeast",
    "frontal cortex",
    "hippocampus",
    "iPSC",
    "iPSC NPC",
    "iPSC motor neurons",
    "input",
    "motor neurons",
    "mushroom bodies",
    "olfactory bulb",
    "oligo",
    "primary AML",
    "primary neurons",
    "spinal cord",
    "striatum-thalamus",
    "temp",
    "temporal cortex",
    "yeast",
    "AF9",
    "HCT116",
    "Jurkat",
    "OC13",
    "myoblast",
    "rhabdomyosarcoma",
]
 