# Generated by Django 3.2.9 on 2021-11-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nextflow', '0002_auto_20211114_1757'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='django_nextflow.pipeline'),
        ),
    ]
