# Generated by Django 3.2.9 on 2021-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data_params',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='job',
            name='params',
            field=models.JSONField(default='{}'),
        ),
    ]
