# Generated by Django 3.2.9 on 2021-12-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20211201_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data_params',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='job',
            name='params',
            field=models.TextField(default='{}'),
        ),
    ]
