# Generated by Django 3.2 on 2021-09-25 12:28

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nextflow', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('output_type', models.CharField(max_length=200)),
                ('post_task', models.CharField(blank=True, max_length=100, null=True)),
                ('can_create_sample', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commands',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.IntegerField(default=time.time)),
                ('last_modified', models.IntegerField(default=time.time)),
                ('started', models.IntegerField(blank=True, null=True)),
                ('finished', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('warning', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('nf_terminal', models.TextField(blank=True, null=True)),
                ('nf_id', models.CharField(blank=True, max_length=100, null=True)),
                ('input', models.TextField(default='{}')),
                ('output', models.TextField(default='{}')),
                ('private', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='samples.collection')),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='execution.command')),
                ('demultiplex_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demultiplexed', to='execution.execution')),
                ('downstream', models.ManyToManyField(related_name='upstream', to='execution.Execution')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_executions', to='core.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='execution.execution')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='samples.sample')),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='NextflowProcess',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=40)),
                ('workdir', models.CharField(max_length=200)),
                ('stdout', models.TextField()),
                ('stderr', models.TextField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextflow_processes', to='execution.execution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutionUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share'], [4, 'own']], default=1)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.execution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'execution_user_links',
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='users',
            field=models.ManyToManyField(related_name='executions', through='execution.ExecutionUserLink', to='core.User'),
        ),
    ]
