# Generated by Django 2.2.20 on 2021-11-14 17:57

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('django_nextflow', '0002_auto_20211114_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created', models.IntegerField(default=time.time)),
                ('last_modified', models.IntegerField(default=time.time)),
                ('description', models.TextField(blank=True, default='')),
                ('private', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField(default=time.time)),
                ('modified', models.IntegerField(default=time.time)),
                ('started', models.IntegerField(null=True)),
                ('finished', models.IntegerField(null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='samples.Collection')),
                ('execution', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='django_nextflow.Execution')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.IntegerField(default=time.time)),
                ('modified', models.IntegerField(default=time.time)),
                ('private', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('qc_pass', models.BooleanField(null=True)),
                ('qc_message', models.CharField(max_length=100)),
                ('pi_name', models.CharField(max_length=100)),
                ('annotator_name', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.Collection')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='django_nextflow.Data')),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Uploadable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('filetype', models.CharField(max_length=20)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadables', to='django_nextflow.Pipeline')),
            ],
            options={
                'db_table': 'uploadables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share']], default=1)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'sample_user_links',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='users',
            field=models.ManyToManyField(related_name='samples', through='samples.SampleUserLink', to='core.User'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='samples.Collection')),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='JobUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share']], default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'job_user_links',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='samples.Sample'),
        ),
        migrations.CreateModel(
            name='DataUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share']], default=1)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nextflow.Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'data_user_links',
            },
        ),
        migrations.CreateModel(
            name='CollectionUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share'], [4, 'own']], default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'collection_user_links',
            },
        ),
        migrations.CreateModel(
            name='CollectionGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[[1, 'access'], [2, 'edit'], [3, 'share']], default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Collection')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
            options={
                'db_table': 'collection_group_links',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='groups',
            field=models.ManyToManyField(related_name='collections', through='samples.CollectionGroupLink', to='core.Group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='users',
            field=models.ManyToManyField(related_name='collections', through='samples.CollectionUserLink', to='core.User'),
        ),
    ]
